Switch to using npm for package @voibo/desktop-audio-capture instead of git submodule
voibo/voibo pull request #10
Opened 2024-12-03 18:08 UTC by kechako

Package desktop-audio-capture uses Node addons and was initially managed
as a Git submodule. However, this approach is not standard practice.
Ideally, the package should be managed through npm. Therefore, this
change transitions the package management from a Git submodule to npm.

- Remove package desktop-audio-capture submodule from third_party directory.
- Remove package bindings from npm dependencies.
- Add package @voibo/desktop-audio-capture to dependencies using npm.
- Update existing code to import and use pacakge
  @voibo/desktop-audio-capture.
- Add package @voibo/desktop-audio-capture to externals in webpack.config.ts.
- Remove the configuration in webpack.config.ts for copying native
  modules of desktop-audio-capture.
- Add Node addon binary path for package @viobo/desktop-audio-capture to
  "asarUnpack" in electron-builder build configuration.

This change requires the installation of tools such as cmake and gcc,
which are necessary to build the native code for the Node addon.

2024-12-03 23:20 UTC, kinisn submitted a review, later dismissed
LGTM

2024-12-05 08:07 UTC, nlin-work commented
Windows build requires a new version of desktop-audio-capture package. 

@kechako :
1. Please check the following commits in the desktop-audio-capture repository: 
- https://github.com/voibo/desktop-audio-capture/commit/e36874ab6d492e4b85af572156be5c0148e69e97
- https://github.com/voibo/desktop-audio-capture/commit/54befea9be55780725a3d7210bd150e029083934
- https://github.com/voibo/desktop-audio-capture/commit/ff24ae80925fe2df21e9e4bc8baff89f500c555a

2. If it looks OK, then please publish a new desktop-audio-capture package and update voibo's package.json to use the new package.

2024-12-05 08:08 UTC, nlin-work requested changes
Windows build requires a new version of desktop-audio-capture package.

@kechako :

1.  Please check the following commits in the desktop-audio-capture repository:

- https://github.com/voibo/desktop-audio-capture/commit/e36874ab6d492e4b85af572156be5c0148e69e97
- https://github.com/voibo/desktop-audio-capture/commit/54befea9be55780725a3d7210bd150e029083934
- https://github.com/voibo/desktop-audio-capture/commit/ff24ae80925fe2df21e9e4bc8baff89f500c555a

2. If it looks OK, then please publish a new desktop-audio-capture package and update voibo's package.json to use the new package.

2024-12-06 09:19 UTC, nlin-work commented on package.json
> +    "@voibo/desktop-audio-capture": "^1.0.0-beta.4",
Need to update to 1.0.0-beta.5

2024-12-06 09:20 UTC, nlin-work requested changes
Please update line 78 of package.json to use 1.0.0-beta.5 of @voibo/desktop-audio-capture

2024-12-06 09:23 UTC, kechako commented
The changes were not included in the commit.
I am pushing the latest commit now.

2024-12-06 09:30 UTC, nlin-work approved these changes

2024-12-06 09:31 UTC, merged